### ISSUE TITLE
Page crash.

### ISSUE THREAD

**Issue by elijahlrc** [szhu/3030#1] opened 2015-09-20 22:03 UTC
The page when you hover over the walls of the maze. /s

**Comment by szhu** [comment] 2015-09-20 22:19
Whoa, that's really weird. Looks like it might be a Chromium bug: [crbug.com/533361](https://code.google.com/p/chromium/issues/detail?id=533361)

I'll update this issue when this gets fixed upstream. :)

**Comment by scott113341** [comment] 2015-09-20 23:04
:+1:

**Comment by ivyreese** [comment] 2015-09-20 23:36
:lollipop:

**Comment by tacone** [comment] 2015-09-20 23:55
:cat:

**Comment by vikashbajaj** [comment] 2015-09-21 00:10
It crashes my facebook tab aswell :laughing:

**Comment by szhu** [comment] 2015-09-21 00:13
Usually Chrome runs each tab in a new process, but when you click a link that opens in a new tab, Chrome does not create a new process for that new tab. That's why your referrer tab is crashing as well.

**Comment by vikashbajaj** [comment] 2015-09-21 00:15
Ok, you guys should try posting as a link on a group on Facebook, so when facebook will try to load a preview on whosever feed it choses to show this post on, their tab will crash :smiling_imp:

**Comment by kernel-io** [comment] 2015-09-21 00:36
when is this going to be fixed? this is worthless to me if it keeps crashing!!

**Comment by danieltanfh95** [comment] 2015-09-21 01:18
Isn't the game is supposed to crash when we hover over the link? :laughing:

**Comment by szhu** [comment] 2015-09-21 01:21
For now, yes, but it's a serious Chrome bug that needs fixed to be soon as possible. Unfortunately, there's nothing I can do about this for now. I will update this issue when it gets fixed upstream.

**Comment by dav-s** [comment] 2015-09-21 01:54
I think somebody found a solution [here](http://github.com/%%30%30) :)

**Comment by lukerollans** [comment] 2015-09-21 03:04
@EpicDavi If a comment could be liked..

**Comment by madelinecameron** [comment] 2015-09-21 03:11
@EpicDavi Jerk. I fell for that.

**Comment by szhu** [comment] 2015-09-21 10:08
This issue was also reported here:  
https://www.reddit.com/r/programming/comments/3lqied/3030_a_game/cv8iz1i?context=1

**Comment by felipegtx** [comment] 2015-09-21 14:19
I'm confused on how to proceed when you create an issue that is related to an error that is actually the main feature of the repo.

**Comment by joshmanders** [comment] 2015-09-21 15:18
Ohhhh @EpicDavi totally got me. :100:

**Comment by valenfys** [comment] 2015-09-22 18:58
> I will update this issue when it gets fixed upstream.

New version of Chrome just came out (45.0.2454.99) and the ~~bug~~ API seems to still work

**Comment by szhu** [comment] 2015-09-22 18:59
I can confirm that feature still works in 45.0.2454.99.

**Comment by szhu** [comment] 2015-09-24 22:50
**This bug is fixed in Chrome 45.0.2454.101.**

https://code.google.com/p/chromium/issues/detail?id=533361#c86

Thanks for playing, everyone!

**Closed as completed** 2015-09-24 22:50 UTC
